language: ruby
rvm:
- 2.1
 
addons:
   apt:
      packages:
         - libssl1.0.0
         - libcurl4-openssl-dev

before_script:
 - ./scripts/build_site

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./scripts/travis_test

# branch whitelist, only for GitHub Pages and a branch for testing
branches:
  only:
  - master
  - dev

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

