#!/bin/sh

#create ward pages
cd docs/wards
cat ../../ward_list | while read I; do 
   rm $I 2>/dev/null
   ln -s ../_includes/ward-template.html $I
done
echo $(wc -l ../../ward_list | awk '{print $1}') wards created
cd ../..

cd docs
jekyll build -d ../_site
