#!/bin/sh
BASEDIR=`dirname $0`
cd "$BASEDIR/../"

cd _site
htmlproofer --assume-extension \
   --url-ignore \
   "/jasone.ca/,/shannonadshade.com/,/elections.ontarioschooltrustees.org/WhatDoTrusteesDo/SchoolBoardTrustees.aspx/,/kevindupuis.com/"
