#!/bin/sh
BASEDIR=`dirname $0`
cd "$BASEDIR/../"

cd _site
htmlproofer --assume-extension \
   --url-ignore \
   "/jasone.ca/,/shannonadshade.com/,/dhshpatel.ca/,/jasonhouse.ca/,/elliotfung.ca/,/elections.ontarioschooltrustees.org/WhatDoTrusteesDo/SchoolBoardTrustees.aspx/,/www.nataliewaddell.ca/"
